export const rafeeqi_role_ids = {
  view_dashboard: "681dbf6a766101d3fcc30b31",
  push_notifications: "6826e75583ea4609fe395ccc",
  view_notifications: "6826e7cf83ea4609fe395d42",
  add_customer: "681dc688766101d3fcc30bc2",
  delete_customer: "681dc694766101d3fcc30bc4",
  edit_customer: "681dc6a3766101d3fcc30bc6",
  view_customer: "681dc6b9766101d3fcc30bc8",
  change_customer_status: "682341d532827fbae613c86f",
  add_partner: "681dc6d5766101d3fcc30bca",
  delete_partner: "681dc6e9766101d3fcc30bde",
  edit_partner: "681dc6f4766101d3fcc30bf2",
  view_partner: "681dc700766101d3fcc30bf4",
  change_partner_status: "682327d6f45e85be4e865133",
  add_user: "681dc73d766101d3fcc30c08",
  delete_user: "681dc749766101d3fcc30c0a",
  edit_user: "681dc752766101d3fcc30c0c",
  view_user: "681dc75b766101d3fcc30c0e",
  change_user_status: "6823442d32827fbae613cb41",
  add_role: "681dc768766101d3fcc30c10",
  delete_role: "681dc775766101d3fcc30c12",
  edit_role: "681dc783766101d3fcc30c14",
  view_role: "681dc78d766101d3fcc30c16",
  change_role_status: "68234db9454f246b3716bedd",
  view_inquiry: "6822fb429491292e2cf0c9c8",
  delete_inquiry: "6822fbf39491292e2cf0c9e7",
  view_employee: "emp001_view",
  add_employee: "emp002_add",
  edit_employee: "emp003_edit",
  delete_employee: "emp004_delete",
};

export const rafeeqi_roles = [
  {
    id: 1,
    title: "Dashboard",
    title_key: "dashboard",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.view_dashboard,
        module_id: 1,
        is_active: false,
        title: "View Dashboard",
        title_key: "view_dashboard",
      },
    ],
  },
  {
    id: 18,
    title: "Notifications",
    title_key: "notifications",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.push_notifications,
        module_id: 1,
        is_active: false,
        title: "Push Notifications",
        title_key: "push_notifications",
      },
      {
        id: rafeeqi_role_ids.view_notifications,
        module_id: 1,
        is_active: false,
        title: "View Notifications",
        title_key: "view_notifications",
      },
    ],
  },
  {
    id: 10,
    title: "Partner",
    title_key: "partner",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.add_partner,
        module_id: 10,
        is_active: false,
        title: "Add Partner",
        title_key: "add_partner",
      },
      {
        id: rafeeqi_role_ids.delete_partner,
        module_id: 10,
        is_active: false,
        title: "Delete Partner",
        title_key: "delete_partner",
      },
      {
        id: rafeeqi_role_ids.edit_partner,
        module_id: 10,
        is_active: false,
        title: "Edit Partner",
        title_key: "edit_partner",
      },
      {
        id: rafeeqi_role_ids.view_partner,
        module_id: 10,
        is_active: false,
        title: "View Partner",
        title_key: "view_partner",
      },
      {
        id: rafeeqi_role_ids.change_partner_status,
        module_id: 10,
        is_active: false,
        title: "Change Partner Status",
        title_key: "change_partner_status",
      },
    ],
  },
  {
    id: 17,
    title: "Inquiry",
    title_key: "inquiry",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.view_inquiry,
        module_id: 17,
        is_active: false,
        title: "View Inquiry",
        title_key: "view_inquiry",
      },
      {
        id: rafeeqi_role_ids.delete_inquiry,
        module_id: 17,
        is_active: false,
        title: "Delete Inquiry",
        title_key: "delete_inquiry",
      },
    ],
  },
  {
    id: 9,
    title: "Customer",
    title_key: "customer",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.add_customer,
        module_id: 9,
        is_active: false,
        title: "Add Customer",
        title_key: "add_customer",
      },
      {
        id: rafeeqi_role_ids.delete_customer,
        module_id: 9,
        is_active: false,
        title: "Delete Customer",
        title_key: "delete_customer",
      },
      {
        id: rafeeqi_role_ids.edit_customer,
        module_id: 9,
        is_active: false,
        title: "Edit Customer",
        title_key: "edit_customer",
      },
      {
        id: rafeeqi_role_ids.view_customer,
        module_id: 9,
        is_active: false,
        title: "View Customer",
        title_key: "view_customer",
      },
      {
        id: rafeeqi_role_ids.change_customer_status,
        module_id: 9,
        is_active: false,
        title: "Change Customer Status",
        title_key: "change_customer_status",
      },
    ],
  },
  {
    id: 11,
    title: "User",
    title_key: "user",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.add_user,
        module_id: 11,
        is_active: false,
        title: "Add User",
        title_key: "add_user",
      },
      {
        id: rafeeqi_role_ids.delete_user,
        module_id: 11,
        is_active: false,
        title: "Delete User",
        title_key: "delete_user",
      },
      {
        id: rafeeqi_role_ids.edit_user,
        module_id: 11,
        is_active: false,
        title: "Edit User",
        title_key: "edit_user",
      },
      {
        id: rafeeqi_role_ids.view_user,
        module_id: 11,
        is_active: false,
        title: "View User",
        title_key: "view_user",
      },
      {
        id: rafeeqi_role_ids.change_user_status,
        module_id: 11,
        is_active: false,
        title: "Change User Status",
        title_key: "change_user_status",
      },
    ],
  },
  {
    id: 12,
    title: "Role",
    title_key: "role",
    is_active: false,
    sub_modules: [
      {
        id: rafeeqi_role_ids.add_role,
        module_id: 12,
        is_active: false,
        title: "Add Role",
        title_key: "add_role",
      },
      {
        id: rafeeqi_role_ids.delete_role,
        module_id: 12,
        is_active: false,
        title: "Delete Role",
        title_key: "delete_role",
      },
      {
        id: rafeeqi_role_ids.edit_role,
        module_id: 12,
        is_active: false,
        title: "Edit Role",
        title_key: "edit_role",
      },
      {
        id: rafeeqi_role_ids.view_role,
        module_id: 12,
        is_active: false,
        title: "View Role",
        title_key: "view_role",
      },
      {
        id: rafeeqi_role_ids.change_role_status,
        module_id: 12,
        is_active: false,
        title: "Change Role Status",
        title_key: "change_role_status",
      },
    ],
  },
];
