/** Default form values for Add Supplier (matches select option `id` values). */
export const DEFAULT_ADD_SUPPLIER_VALUES = {
  name: "",
  email: "",
  phone: "",
  emergencyPhone: "",
  address: "",
  country: "",
  city: "",
  supplierType: "Company",
  taxNumber: "",
  registrationNumber: "",
  licenseNumber: "",
  licenseExpiryDate: "",
  status: "Active",
  contactPersonName: "",
  contactPersonPhone: "",
  contactPersonEmail: "",
  contactPersonDesignation: "",
  bankName: "",
  accountTitle: "",
  accountNumber: "",
  iban: "",
  branchCode: "",
  swift: "",
};
